---
title: "World oil production"
author: "Ivar Refsdal"
date: "4/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)

# https://www.eia.gov/totalenergy/data/browser/?tbl=T11.01B&fbclid=IwAR0UMyPJ_9DhYMeMzn7FLcDsC0lPs8xc1b_NBB8_94RiExxx5ntB4jGy2uk#/?f=M&start=197301&end=201812&charted=0-11-12

url <- "https://www.eia.gov/totalenergy/data/browser/csv.php?tbl=T11.01B"
fil <- "MER_T11_01B.csv"
download.file(url, destfile=fil, method="libcurl")
df_org <- read_csv(fil, guess_max = 10000)

df <- df_org %>%
  select(-c(MSN)) %>%
  mutate(YYYYMM = as.character(YYYYMM)) %>%
  mutate(Description = str_replace(Description, "Crude Oil Production, ", "")) %>%
  mutate(Value = as.double(Value)) %>%
  filter(endsWith(YYYYMM, "13"), # 13 means annual production
         Description == "World") %>%
  mutate(YYYYMM = str_replace(YYYYMM, "13$", "")) %>%
  mutate(year = as.Date(YYYYMM, format="%Y")) %>%
  arrange(year)

ggplot(df, aes(x = year, y = Value)) +
  geom_bar(stat="identity")
```


```{r}
library(tidyverse)
library(zoo)
library(lubridate)

# https://www.eia.gov/totalenergy/data/browser/?tbl=T11.01B&fbclid=IwAR0UMyPJ_9DhYMeMzn7FLcDsC0lPs8xc1b_NBB8_94RiExxx5ntB4jGy2uk#/?f=M&start=197301&end=201812&charted=0-11-12

url <- "https://www.eia.gov/totalenergy/data/browser/csv.php?tbl=T11.01B"
fil <- "MER_T11_01B.csv"
download.file(url, destfile=fil, method="libcurl")
df_org <- read_csv(fil, guess_max = 10000)

df <- df_org %>%
  select(-c(MSN, Column_Order)) %>%
  mutate(Description = str_replace(Description, "Crude Oil Production, ", "")) %>%
  mutate(YYYYMM = as.character(YYYYMM)) %>%
  filter(!endsWith(YYYYMM, "13"), # 13 means annual production
         Description == "World") %>%
  mutate(date = ceiling_date(ymd(YYYYMM, truncated= 1), "month") - days(1)) %>%
  select(YYYYMM, date, everything()) %>%
  mutate(Value = as.double(Value)) %>%
  arrange(YYYYMM) %>%
  mutate(Value2 = rollmean(x = Value, k = 12, align = "right", fill = NA) / 1000) %>%
  remove_missing()

  ggplot(df, aes(x = date, y = Value2)) +
  geom_line(aes(group = Description)) +
  labs(title="Global råoljeproduksjon",
       subtitle="12 månadar glidande gjennomsnitt",
       x="År",
       y="Millionar fat per dag")
```
